random_radio = ["http://stream01.iloveradio.de/iloveradio1.mp3",
                "http://br-br1-obb.cast.addradio.de/br/br1/obb/mp3/128/stream.mp3",
                "http://mp3channels.webradio.antenne.de:80/antenne",
                "http://fhin.4broadcast.de/galaxyin.mp3",
                "http://hr-youfm-live.cast.addradio.de/hr/youfm/live/mp3/128/stream.mp3",
                "http://mp3.planetradio.de/planetradio/hqlivestream.mp3",
                "http://mp3channels.webradio.antenne.de/rockantenne",
                "http://mp3stream7.apasf.apa.at:8000",
                "http://raj.krone.at:80/kronehit-ultra-hd.aac",
                "http://radio.vgmradio.com:8040/stream",
                "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p",
                "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p",
                "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio3_mf_p",
                "http://us2.internet-radio.com:8281/live",
                "http://64.71.79.181:8040/",
                "http://64.71.79.181:8018/",
                "http://ibizaglobalradio.streaming-pro.com:8024/"]